name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          extensions: ldap, intl
          ini-values: post_max_size=256M, short_open_tag=Off
          coverage: xdebug
          tools: none
      - name: Install dependencies
        run: cd src/ && composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Test with phpunit
        run: cd src/ && vendor/bin/phpunit --coverage-text